[package]
name = "node_binding"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2.12.2", features = ["tokio_rt", "napi4"] }
napi-derive = "2.12.2"
tokio = { version = "1.48.0", features = ["full"] }
